services:
  - type: web
    name: mediamate-backend
    runtime: docker
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        sync: false
      - key: BASE_DIR
        value: /tmp/mediamate
    healthCheckPath: /api/info
